# Generated by Django 3.1.4 on 2021-07-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210719_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='presciption',
            field=models.CharField(default='Write here', max_length=600),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
    ]
